force-app/main/default/objects/Account/fields/Shoe_Size__c.field-meta.xml
<CustomField>
    <fullName>Shoe_Size__c</fullName>
    <label>Shoe Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>6.5</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>7.5</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>8.5</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>9.5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>10.5</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>11.5</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>12.5</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>13.5</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>14.5</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>15.5</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/T_shirt_size__c.field-meta.xml
<CustomField>
    <fullName>T_shirt_size__c</fullName>
    <label>T-shirt size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XS</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>XL</fullName>
            </value>
            <value>
                <fullName>XXL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountCustomerDetailsQueueable.cls
/*
* @Purpose: Queueable class to for commutatus callout handle
* @Author: Gaurav Fugat
* @CreatedDate: 06/10/2024
* @Test Class: not created yet
* @LastModifiedDate: 
* @LastModifiedBy: 
*/
public class AccountCustomerDetailsQueueable implements Queueable, Database.AllowsCallouts {
    
    // List of accounts to process
    private List<Account> accountList;
    
    // Constructor to pass account list
    public AccountCustomerDetailsQueueable(List<Account> accounts) {
        this.accountList = accounts;
    }
    
    // Execute method for queueable processing
    public void execute(QueueableContext context) {
        // Iterate over the list of accounts and call the sendCustomerDetails method
        for (Account acc : accountList) {
            if (acc.PersonEmail != null && acc.T_shirt_size__c != null && acc.Shoe_Size__c != null) {
                // Calling the future method to send customer details
                accountTriggerHandler.sendCustomerDetails(acc.Id, acc.PersonEmail, acc.T_shirt_size__c, acc.Shoe_Size__c);
            } else {
                System.debug('Account ' + acc.Id + ' is missing required fields.');
            }
        }
    }
}